# Generated by Django 4.2.4 on 2023-08-19 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
