# Generated by Django 4.2.4 on 2023-08-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapplication', '0003_customer_invoice_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='progress',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notice_to_consider',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
