# Generated by Django 4.2.4 on 2023-08-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapplication', '0004_customer_progress_invoice_notice_to_consider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
