# Generated by Django 4.2.4 on 2023-08-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapplication', '0006_alter_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
