# Generated by Django 4.2.4 on 2023-08-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapplication', '0007_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notice',
            field=models.TextField(blank=True),
        ),
    ]
